### ISSUE TITLE
Logging frå harvest.py kjem ikkje ut i kubernetes log

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-harvest-scheduler#25]
Logging frå src/scheduler.py kjem ut i loggen, men det gjer ikkje jobs/harvest.py sjølv om det logges på same måten. Vurder eventuelt å ikkje skrive log til fil.

(Dette problemet oppstår ikkje når tjenesten køyrer i docker-compose lokalt.)

**Comment by valosnah** [comment]
Det ser ut som dette er fikset

**Comment by stigbd** [comment]
Hugsar ikkje. Men om det ser bra ut no, lukker vi.
