### ISSUE TITLE
Vurdering av logging

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-harvest-scheduler#44]
Absolutt alt er tolket som INFO. Uvisst om dette er riktig

![image](https://user-images.githubusercontent.com/8625716/109005435-3aec1380-76aa-11eb-9546-0db7b15272c7.png)

**Comment by valosnah** [comment]
Alt jeg kan se i loggen er logget korrekt. Kan vurdere å åpne igjen om vi skulle se noe annet.

**Comment by shenluna** [comment]
Sjekket i stag, og verifisert av Hans Olav
